apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "presidio.fullname" . }}
  labels:
    app.kubernetes.io/name: presidio
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: presidio
      app.kubernetes.io/instance: {{ .Release.Name }}
