apiVersion: v1
kind: Service
metadata:
  name: {{ include "presidio.fullname" . }}-analyzer
  labels:
    app.kubernetes.io/name: presidio
    app.kubernetes.io/component: analyzer
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: presidio
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "presidio.fullname" . }}-anonymizer
  labels:
    app.kubernetes.io/name: presidio
    app.kubernetes.io/component: anonymizer
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: presidio
    app.kubernetes.io/instance: {{ .Release.Name }}
