apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-python-executor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: python-executor
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: python-executor
    app.kubernetes.io/instance: {{ .Release.Name }}
