apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap-nginx-conf.yaml
  - configmap-policy.yaml
  - configmap-data.yaml
  - configmap-opa-config.yaml
