{{- if .Values.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name }}
  labels:
    {{- include "envoy-gateway.labels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.gatewayClass.controllerName }}
  {{- if .Values.envoyProxy }}
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ .Values.gatewayClass.name }}-proxy
    namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
