apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgbouncer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pgbouncer
      protocol: TCP
      name: pgbouncer
  selector:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/instance: {{ .Release.Name }}
