apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "llm-guard.fullname" . }}
  labels:
    app.kubernetes.io/name: llm-guard
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llm-guard
      app.kubernetes.io/instance: {{ .Release.Name }}
