enabled: true

gateway:
  name: agentshield-gateway
  hostname: "agentshield.127.0.0.1.nip.io"
  langfuseHostname: "langfuse.127.0.0.1.nip.io"
  port: 80
  tls:
    enabled: true
    secretName: gateway-tls

gatewayClass:
  name: agentshield
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
